#!/usr/bin/env python3
"""The false-positive rate on out-of-domain text I did not choose.

## Why a mechanical set

Every refusal set so far was hand-authored by the same person who wrote the
resolver, which is a fair objection: holdout 1 was authored before the
domain check and MISSED at 0.80; holdout 2 was authored after and fired at
0.9167, and no amount of care removes the possibility that I picked
questions the fix would handle.

So this set is not chosen at all. It is sampled mechanically from Open
English WordNet — example sentences where a synset has one, glosses
otherwise — with a fixed seed. WordNet describes everyday concepts:
animals, tools, weather, furniture, emotions. A corpus of mathematical
statements should refuse essentially all of it, and nothing about the
sampling knows what the resolver finds difficult.

**No filtering.** Sentences are not screened for mathematical content, so a
handful of genuinely quantitative ones will be in the sample and will
resolve correctly. That inflates the measured false-positive rate rather
than deflating it, which is the direction an honest measurement should err.

## Registered prediction (frozen before the first run)

- **F1.** On 500 mechanically sampled WordNet sentences, fewer than **10%**
  reach a corpus statement. This is the number the hand-authored refusal
  arms were estimating from twelve examples each; here it is estimated from
  five hundred that nobody selected.

F1 is a claim about *arbitrary* text in the plainest sense available: text
generated by a process with no knowledge of this project. If it misses, the
honest report is that the false-positive rate on unselected input is higher
than the curated sets suggested, and the curated numbers were optimistic.
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts"))

from gloss import archive_path  # noqa: E402
from resolver import ASK, BIND, default_index, resolve  # noqa: E402
from wordnet_store import WordNetIndex  # noqa: E402

DEFAULT_OUT = REPO / "experiments" / "false_positive_rate.json"
SAMPLE_SEED = 20260817
SAMPLE_SIZE = 500
THRESHOLD = 0.10


def sentences(limit: int, seed: int) -> list[str]:
    """Everyday English, sampled with a fixed seed. No screening."""
    archive = archive_path()
    if archive is None:
        return []
    index = WordNetIndex.load(archive)
    pool: list[str] = []
    for synset_id in sorted(index.synsets):
        synset = index.synsets[synset_id]
        for text in (*synset.examples, *synset.definitions):
            cleaned = " ".join(str(text).split())
            # Long enough to be a sentence, short enough to be a question a
            # person might type.
            if 20 <= len(cleaned) <= 120:
                pool.append(cleaned)
                break
    random.Random(seed).shuffle(pool)
    return pool[:limit]


def run(out_path: Path, limit: int, seed: int) -> dict:
    texts = sentences(limit, seed)
    if not texts:
        return {"skipped": "no WordNet archive; set COROLLARY_WORDNET"}
    index = default_index()
    claimed: list[dict] = []
    for text in texts:
        outcome = resolve(text, index)
        if outcome.kind in {BIND, ASK}:
            claimed.append({
                "text": text,
                "kind": outcome.kind,
                "detail": outcome.detail[:110],
                "top": outcome.candidates[0] if outcome.candidates else None,
            })
    rate = len(claimed) / len(texts)
    result = {
        "schema": "false_positive_rate.v1",
        "source": "Open English WordNet examples/glosses, unscreened",
        "seed": seed,
        "sampled": len(texts),
        "claimed": len(claimed),
        "false_positive_rate": round(rate, 4),
        "adjudication": {
            "F1": {
                "fired": rate < THRESHOLD,
                "rate": round(rate, 4),
                "threshold": THRESHOLD,
            }
        },
        "claimed_samples": claimed[:25],
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    return result


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--limit", type=int, default=SAMPLE_SIZE)
    ap.add_argument("--seed", type=int, default=SAMPLE_SEED)
    args = ap.parse_args(argv)
    result = run(args.out, args.limit, args.seed)
    print(json.dumps(
        {k: v for k, v in result.items() if k != "claimed_samples"}, indent=2
    ))
    for row in result.get("claimed_samples", [])[:12]:
        print(f"  [{row['kind']}] {row['text']}")
        print(f"        -> {row['top']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
