#!/usr/bin/env python3
"""The registered run — B1-B8, B10-B13, the controls, and R1.

`docs/DESIGN-session-ledger.md` §7 is the construction gate, §8 is the blind
control and the voiding sentence, §9 is R1. The numbers were frozen in the
design before this file existed and re-frozen verbatim in
`experiments/session_ledger_prereg.json`; this script scores them and writes
`experiments/session_ledger_run.json`.

**Half B's first execution is the registered run.** Half A is available for
debugging and is scored beside half B wherever a clause is corpus-wide, but
the verdicts that license anything are half B's.

## The mixer is sealed and the scorer is blind

§8: *"Mutations for B4/B5/B6 are generated by one sealed script mixing the
three arms; the scorer sees no arm labels until after scoring."* That is
mechanical here, not a promise. :func:`build_cases` returns two objects — a
shuffled case list carrying an opaque `case_id` and **no arm field**, and a
separate key mapping `case_id` to its arm. :func:`score_cases` is handed only
the first, records only `(case_id, flipped?, replayed status)`, and the join
against the key is the last step of the run. The seed is the string frozen
in the prereg.

Every case has the same shape whatever arm it belongs to — a journal
mutation and one turn to watch — so the scorer cannot infer an arm from the
case's structure either. A blindness that a scorer could see through by
looking at a field name would be ceremony.

## What this run does not do

It does not decide whether any answer was right. §10: *sessions are
reproducible, not correct, and a wrong answer replays as faithfully as a
right one.* Every verdict below is about bytes.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import random
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
if str(REPO / "scripts") not in sys.path:
    sys.path.insert(0, str(REPO / "scripts"))

import session_ledger as ledger  # noqa: E402
import replay_session  # noqa: E402
from harness import CoreSession, route_line  # noqa: E402

PREREG = "experiments/session_ledger_prereg.json"
SEAL = "experiments/session_corpus_seal.json"
ARTIFACT = "experiments/session_ledger_run.json"
RUN_SCHEMA = "corollary.session-ledger-run/1"
AUDIT_MARKS = "experiments/session_b13_audit_marks.json"

#: How many B6 cases the mixer may draw from one half-B session. Two, not
#: one, because half B holds 25 sessions and B6's registered floor is >=30:
#: at one per session the generator's CEILING was below the floor it fed.
B6_PER_SESSION = 2

#: The registered denominators, so a clause can go red for having too few
#: cases and not only for flipping. A verdict that checks the numerator and
#: not the denominator is a green assertion that could not have gone red.
REGISTERED_DENOMINATORS = {"B5": 60, "B6": 30, "B8": 20}


def _rng(seed_string: str) -> random.Random:
    """The prereg's frozen derivation, written out there and applied here."""

    return random.Random(
        int(hashlib.sha256(seed_string.encode("utf-8")).hexdigest()[:16], 16)
    )


def _load(path: str) -> dict:
    return json.loads((REPO / path).read_text(encoding="utf-8"))


def _journal(entry: dict) -> dict:
    return json.loads((REPO / entry["journal"]).read_text(encoding="utf-8"))


def _read_log(entry: dict) -> dict:
    return json.loads((REPO / entry["read_log"]).read_text(encoding="utf-8"))


# --------------------------------------------------------------------------
# B1 — order, read off git rather than asserted
# --------------------------------------------------------------------------


def _first_commit(path: str) -> str:
    out = subprocess.run(
        ["git", "log", "--diff-filter=A", "--format=%H %cI", "--", path],
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    lines = [line for line in out.stdout.splitlines() if line.strip()]
    return lines[-1] if lines else ""


def score_b1(seal: dict) -> dict:
    """B1, both clauses, adjudicated separately because they differ in kind.

    Clause 2 — *any edit to a sealed journal or the seal voids the run* — is
    mechanical and is checked against the seal's own digests.

    Clause 1 — *P3's seal exists before the replayer is written* — is an
    ORDERING claim, and this run does not meet it as literally registered.
    The order is published rather than reinterpreted: the commission that
    built this slice put the machinery (including `scripts/replay_session.py`)
    before the recording, so the replayer was committed while
    `experiments/sessions/` did not exist.

    What that costs, stated in both directions rather than only the
    convenient one. B1's order protects against a replayer FITTED TO a
    frozen corpus. The order actually taken gives that protection in a
    stronger form — the replayer could not be fitted to journals that did
    not exist — and gives up the mirror protection, that a corpus not be
    authored to suit an existing replayer. The corpus WAS authored after the
    replayer, by the same hand, so that exposure is real and is the honest
    finding here. Its mitigations are named and none of them is a
    substitute: the authoring script is committed and its six shapes are
    declared; the shapes are assigned by counter, not by half; and the
    replayer's own bytes have not changed since before the corpus existed,
    which git can confirm.
    """

    journal_edits = []
    for entry in seal["sessions"]:
        for key, digest_field in (
            ("journal", "journal_digest"),
            ("read_log", "read_log_digest"),
        ):
            path = REPO / entry[key]
            got = ledger.text_digest(path.read_text(encoding="utf-8"))
            if got != entry[digest_field]:
                journal_edits.append(
                    {
                        "session_id": entry["session_id"],
                        "file": entry[key],
                        "sealed": entry[digest_field],
                        "found": got,
                    }
                )

    replayer = _first_commit("scripts/replay_session.py")
    seal_commit = _first_commit(SEAL)
    return {
        "clause_2_no_sealed_file_was_edited": {
            "verdict": "GREEN" if not journal_edits else "RED",
            "files_checked": 2 * len(seal["sessions"]),
            "edits_found": journal_edits,
        },
        "clause_1_seal_before_replayer": {
            "verdict": "MISSED",
            "replayer_first_committed": replayer,
            "seal_first_committed": seal_commit,
            "what_happened": (
                "the replayer was committed before the seal existed, because "
                "this slice's ordered work put the machinery before the "
                "recording"
            ),
            "what_it_protects_and_what_it_gave_up": (
                "B1's order guards against a replayer fitted to a frozen "
                "corpus; the order taken gives that in a stronger form (the "
                "replayer could not be fitted to journals that did not "
                "exist) and gives up the mirror guard, that a corpus not be "
                "authored to suit an existing replayer. The corpus WAS "
                "authored after the replayer by the same hand. That exposure "
                "is real and is published rather than argued away."
            ),
            "mitigations_that_are_not_substitutes": [
                "the authoring script is committed and its six shapes are "
                "declared in its docstring",
                "shapes are assigned by counter, so the authoring consulted "
                "nothing about which half a session would land in",
                "the replayer's bytes have not changed since before the "
                "corpus existed, and git can confirm it",
            ],
            "does_it_void_the_run": (
                "no, and the reason is registered rather than chosen now: B1 "
                "is not in R1 (§9) and not among §11's stop conditions. The "
                "miss is adjudicated and published, which is what the release "
                "gate asks of B1-B13, and no clause is claimed green that is "
                "not."
            ),
        },
    }


# --------------------------------------------------------------------------
# B2, B3 — replay and pins
# --------------------------------------------------------------------------


def score_b2(seal: dict, pins: dict, index) -> dict:
    started = time.time()
    per_session = []
    reproduced = total = 0
    for entry in seal["sessions"]:
        report = replay_session.replay(
            REPO, _journal(entry), shared_index=index, live_pins=pins
        )
        total += report.turns_total
        reproduced += report.turns_reproduced
        per_session.append(
            {
                "session_id": entry["session_id"],
                "half": entry["half"],
                "turns_total": report.turns_total,
                "turns_reproduced": report.turns_reproduced,
                "first_divergence_turn": report.first_divergence_turn,
                "divergences": report.divergences,
            }
        )
    elapsed = round(time.time() - started, 1)
    misses = [row for row in per_session if row["first_divergence_turn"] is not None]
    return {
        "verdict": "GREEN" if not misses else "RED",
        "denominator": total,
        "denominator_source": "the seal's own turn count, not a round number",
        "turns_reproduced": reproduced,
        "misses_published_individually": misses,
        "elapsed_seconds": elapsed,
        "budget_seconds": 1800,
        "overrun": elapsed > 1800,
        "by_half": {
            half: {
                "turns_total": sum(
                    row["turns_total"] for row in per_session
                    if row["half"] == half
                ),
                "turns_reproduced": sum(
                    row["turns_reproduced"] for row in per_session
                    if row["half"] == half
                ),
            }
            for half in ("A", "B")
        },
    }


def score_b3(seal: dict, pins: dict, index) -> dict:
    """Every pin, every journal, no sampling."""

    results = []
    for entry in seal["sessions"]:
        journal = _journal(entry)
        for field in ledger.PIN_FIELDS:
            perturbed = dict(pins)
            perturbed[field] = f"perturbed-{field}"
            report = replay_session.replay(
                REPO, journal, shared_index=index, live_pins=perturbed
            )
            ok = (
                report.refusal == replay_session.STALE
                and report.pin_mismatch == [field]
                and report.turns_reproduced == 0
            )
            if not ok:
                results.append(
                    {
                        "session_id": entry["session_id"],
                        "pin": field,
                        "refusal": report.refusal,
                        "pin_mismatch": report.pin_mismatch,
                        "turns_reproduced": report.turns_reproduced,
                    }
                )
    total = len(seal["sessions"]) * len(ledger.PIN_FIELDS)
    return {
        "verdict": "GREEN" if not results else "RED",
        "perturbations": total,
        "pins": list(ledger.PIN_FIELDS),
        "sampling": "none — every pin field on every sealed journal",
        "failures": results,
    }


# --------------------------------------------------------------------------
# §8's sealed mixer
# --------------------------------------------------------------------------


def _case_id(payload: dict) -> str:
    return hashlib.sha256(ledger.canonical(payload).encode("utf-8")).hexdigest()[:16]


def build_cases(seal: dict, seed_string: str) -> tuple[list[dict], dict]:
    """One mixer, three arms, and the arm labels kept in a separate object.

    Returns `(cases, key)`. `cases` carries no arm field and is shuffled;
    `key` maps `case_id` to arm and is not consulted until after scoring.
    """

    rng = _rng(seed_string)
    cases: list[dict] = []
    key: dict[str, str] = {}
    half_b = [entry for entry in seal["sessions"] if entry["half"] == "B"]

    def _add(arm: str, payload: dict) -> None:
        case_id = _case_id(payload)
        cases.append({"case_id": case_id, **payload})
        key[case_id] = arm

    # --- B4: mutate one CITED assumption on each binding-dependent turn ---
    for entry in half_b:
        journal = _journal(entry)
        for turn in journal["turns"]:
            if not ledger.is_binding_dependent(turn):
                continue
            assumption_id = turn["assumptions_cited"][0]
            record = next(
                item
                for item in journal["assumptions"]
                if item["assumption_id"] == assumption_id
            )
            atom, polarity = record["normal_form"]
            flip = rng.random() < 0.5
            if flip:
                new_atom, new_polarity = atom, not polarity
                new_text = ("not " + atom) if polarity else atom
            else:
                name, value = atom.split("=", 1)
                new_value = int(value.strip()) + 1 + rng.randrange(3)
                new_atom = f"{name.strip()} = {new_value}"
                new_polarity = polarity
                new_text = new_atom if polarity else f"not {new_atom}"
            _add(
                "B4",
                {
                    "session_id": entry["session_id"],
                    "watch_turn": turn["turn_index"],
                    "mutation": {
                        "kind": "edit",
                        "assumption_id": assumption_id,
                        "text_bytes": new_text,
                        "normal_form": [new_atom, new_polarity],
                    },
                },
            )

    # --- B5: 60 sham assumptions, well formed and never cited -------------
    for number in range(60):
        entry = half_b[number % len(half_b)]
        journal = _journal(entry)
        watch = journal["turns"][number % len(journal["turns"])]["turn_index"]
        name = f"sham{number:02d}"
        _add(
            "B5",
            {
                "session_id": entry["session_id"],
                "watch_turn": watch,
                "mutation": {
                    "kind": "insert",
                    "record": {
                        "assumption_id": f"s{number:03d}",
                        "declared_at_turn": 0,
                        "text_bytes": f"{name} = {number}",
                        "normal_form": [f"{name} = {number}", True],
                        "status": "live",
                        "superseded_by": None,
                        "key_id": "",
                        "mac": "",
                    },
                },
            },
        )

    # --- B6: mutate a LIVE BUT UNCITED assumption, watching one turn ------
    #
    # Up to B6_PER_SESSION cases per half-B session. The first version of
    # this generator took at most ONE, and half B holds 25 sessions, so its
    # ceiling was 25 against a registered floor of >=30 — a generator whose
    # ceiling sits below the floor it feeds, which is §4.0(3)'s
    # unmeetable-floor defect appearing inside the instrument. It produced
    # 21 and the run reported B6 green anyway, because it checked flips and
    # never checked its own denominator. Both halves of that are fixed here
    # and the original run stands unedited (prereg amendment 2).
    for entry in half_b:
        journal = _journal(entry)
        ids = [item["assumption_id"] for item in journal["assumptions"]]
        taken = 0
        for turn in journal["turns"]:
            if taken >= B6_PER_SESSION:
                break
            uncited = [
                item
                for item in ids
                if item not in turn["assumptions_cited"]
                and _declared_by(journal, item) <= turn["turn_index"]
            ]
            if not uncited:
                continue
            assumption_id = uncited[rng.randrange(len(uncited))]
            record = next(
                item
                for item in journal["assumptions"]
                if item["assumption_id"] == assumption_id
            )
            atom, polarity = record["normal_form"]
            if "=" not in atom:
                continue
            name, value = atom.split("=", 1)
            new_atom = f"{name.strip()} = {int(value.strip()) + 7}"
            _add(
                "B6",
                {
                    "session_id": entry["session_id"],
                    "watch_turn": turn["turn_index"],
                    "mutation": {
                        "kind": "edit",
                        "assumption_id": assumption_id,
                        "text_bytes": new_atom if polarity else f"not {new_atom}",
                        "normal_form": [new_atom, polarity],
                    },
                },
            )
            taken += 1
    rng.shuffle(cases)
    return cases, key


def _declared_by(journal: dict, assumption_id: str) -> int:
    for item in journal["assumptions"]:
        if item["assumption_id"] == assumption_id:
            return item["declared_at_turn"]
    return 1 << 30


def _apply(journal: dict, mutation: dict) -> dict:
    """Build the mutated FIXTURE. Never written under experiments/sessions/.

    B4's rule, obeyed for every arm: only the Assumption record moves. No
    turn's `input_bytes` is touched by anything here, which is what makes
    the stateless baseline's score-zero a construction rather than a hope.
    """

    fixture = copy.deepcopy(journal)
    if mutation["kind"] == "insert":
        fixture["assumptions"].append(copy.deepcopy(mutation["record"]))
        return fixture
    for record in fixture["assumptions"]:
        if record["assumption_id"] == mutation["assumption_id"]:
            record["text_bytes"] = mutation["text_bytes"]
            record["normal_form"] = list(mutation["normal_form"])
    return fixture


def score_cases(
    seal: dict, cases: list[dict], pins: dict, index, *, stateless: bool = False
) -> list[dict]:
    """Blind scoring: no case carries an arm and none is looked up."""

    by_id = {entry["session_id"]: entry for entry in seal["sessions"]}
    baseline: dict[str, dict] = {}
    scored = []
    for case in cases:
        entry = by_id[case["session_id"]]
        journal = _journal(entry)
        if case["session_id"] not in baseline:
            baseline[case["session_id"]] = {
                turn["turn_index"]: turn["result"]["answer_bytes_digest"]
                for turn in journal["turns"]
            }
        fixture = _apply(journal, case["mutation"])
        report = replay_session.replay(
            REPO,
            fixture,
            shared_index=index,
            live_pins=pins,
            stateless=stateless,
        )
        watched = [
            item
            for item in report.divergences
            if item["turn_index"] == case["watch_turn"]
        ]
        scored.append(
            {
                "case_id": case["case_id"],
                "session_id": case["session_id"],
                "watch_turn": case["watch_turn"],
                "flipped": bool(watched),
                "replayed_status": watched[0]["replayed_status"] if watched else None,
                "replayed_route": watched[0]["replayed_route"] if watched else None,
            }
        )
    return scored


# --------------------------------------------------------------------------
# B7, B10, B12
# --------------------------------------------------------------------------


def score_b7(seal: dict) -> dict:
    misses, total = [], 0
    for entry in seal["sessions"]:
        for turn in _journal(entry)["turns"]:
            if turn["result"]["kind"] not in ledger.REFUSAL_STATUSES:
                continue
            total += 1
            if not turn["receipt_digest"] or turn["assumptions_cited"] is None:
                misses.append(
                    {
                        "session_id": entry["session_id"],
                        "turn_index": turn["turn_index"],
                        "receipt_digest": turn["receipt_digest"],
                        "assumptions_cited": turn["assumptions_cited"],
                    }
                )
    return {
        "verdict": "GREEN" if not misses else "RED",
        "refusal_turns": total,
        "misses": misses,
        "empty_is_allowed_null_is_red": True,
    }


def score_b10(seal: dict, index) -> dict:
    misses, total = [], 0
    for entry in seal["sessions"]:
        journal = _journal(entry)
        for turn in journal["turns"]:
            if turn["assumptions_cited"]:
                continue
            total += 1
            fresh = CoreSession.boot(
                REPO, offline=True, session_id=entry["session_id"]
            )
            fresh.resolver_index = index
            verdict = route_line(REPO, fresh, turn["input_bytes"])
            if ledger.answer_bytes_digest(verdict) != (
                turn["result"]["answer_bytes_digest"]
            ):
                misses.append(
                    {
                        "session_id": entry["session_id"],
                        "turn_index": turn["turn_index"],
                        "input_bytes": turn["input_bytes"],
                    }
                )
    return {
        "verdict": "GREEN" if not misses else "RED",
        "uncited_turns": total,
        "misses": misses,
    }


def score_b12(seal: dict) -> dict:
    misses, total = [], 0
    for entry in seal["sessions"]:
        journal = _journal(entry)
        log = _read_log(entry)
        from_log: dict[int, set[str]] = {}
        for event in log["events"]:
            from_log.setdefault(event["turn_index"], set()).add(
                event["assumption_id"]
            )
        for turn in journal["turns"]:
            total += 1
            claimed = set(turn["assumptions_cited"])
            corroborated = from_log.get(turn["turn_index"], set())
            if claimed != corroborated:
                misses.append(
                    {
                        "session_id": entry["session_id"],
                        "turn_index": turn["turn_index"],
                        "journal_says": sorted(claimed),
                        "read_log_says": sorted(corroborated),
                    }
                )
    return {
        "verdict": "GREEN" if not misses else "RED",
        "turns_checked": total,
        "uncorroborated": misses,
        "how_the_two_sides_are_independent": (
            "the journal's citation list is a per-turn snapshot taken by "
            "session_ledger.write_journal's caller at turn close; the read "
            "log is written by session_ledger.write_read_log from the "
            "barrier's raw event list. Different functions, different files."
        ),
    }


# --------------------------------------------------------------------------
# B8 — tamper, with the chain repaired
# --------------------------------------------------------------------------


def _repair_chain(journal: dict) -> dict:
    previous = ledger.header_digest(journal["header"])
    for turn in journal["turns"]:
        turn["prev_turn_digest"] = previous
        previous = ledger.digest(turn)
    return journal


def _detect(journal: dict, sealed_digest: str, keyring) -> dict:
    """Detection from MACs and the out-of-band seal ONLY.

    Chain arithmetic is deliberately not consulted: B8's adversary repairs
    the chain, so a detector that reads it would report success on a journal
    it did not actually catch.
    """

    session_id = journal["header"]["session_id"]
    mac_failures = [
        turn["turn_index"]
        for turn in journal["turns"]
        if not ledger.verify_turn_mac(turn, session_id, keyring)
    ] + [
        record["assumption_id"]
        for record in journal["assumptions"]
        if not ledger.verify_assumption_mac(record, session_id, keyring)
    ]
    file_digest = ledger.text_digest(ledger.serialize(journal))
    return {
        "keyed_mac_detected": bool(mac_failures),
        "mac_failures": mac_failures,
        "out_of_band_seal_detected": file_digest != sealed_digest,
        "detected": bool(mac_failures) or file_digest != sealed_digest,
    }


def score_b8(seal: dict, keyring, seed_string: str) -> dict:
    rng = _rng(seed_string + "-tamper")
    half_b = [entry for entry in seal["sessions"] if entry["half"] == "B"]
    chosen = rng.sample(half_b, 20)
    repaired, naive = [], []
    for entry in chosen:
        original = _journal(entry)
        target = rng.randrange(len(original["turns"]))

        tampered = copy.deepcopy(original)
        tampered["turns"][target]["input_bytes"] = "1 + 1"
        naive_result = _detect(
            tampered, entry["journal_digest"], keyring
        )
        naive.append(
            {
                "session_id": entry["session_id"],
                "turn_index": target,
                **naive_result,
            }
        )

        chained = _repair_chain(copy.deepcopy(tampered))
        chained_result = _detect(chained, entry["journal_digest"], keyring)
        repaired.append(
            {
                "session_id": entry["session_id"],
                "turn_index": target,
                "chain_is_internally_consistent": _chain_consistent(chained),
                **chained_result,
            }
        )

    caught = sum(1 for row in repaired if row["detected"])
    by_mac = sum(1 for row in repaired if row["keyed_mac_detected"])
    floor = REGISTERED_DENOMINATORS["B8"]
    return {
        "verdict": (
            "GREEN"
            if caught == floor and len(repaired) == floor
            else "RED"
        ),
        "registered_denominator": floor,
        "denominator_met": len(repaired) == floor,
        "threat_model": (
            "the tamper script rewrites one turn's bytes AND recomputes every "
            "downstream prev_turn_digest consistently — the naive-chain "
            "repair a file-holding adversary would perform. Detection comes "
            "from the keyed MACs (the tamperer holds no key) or the "
            "out-of-band seal digest, never from chain arithmetic, and the "
            "detector does not read the chain at all."
        ),
        "repaired_chain_arm": {
            "cases": 20,
            "detected": caught,
            "detected_by_keyed_mac": by_mac,
            "rows": repaired,
        },
        "unrepaired_chain_arm": {
            "cases": 20,
            "detected": sum(1 for row in naive if row["detected"]),
            "rows": naive,
            "note": (
                "run and reported, but passing only this arm is not passing "
                "B8 — the design says so and this run does not treat it as a "
                "substitute"
            ),
        },
    }


def _chain_consistent(journal: dict) -> bool:
    previous = ledger.header_digest(journal["header"])
    for turn in journal["turns"]:
        if turn["prev_turn_digest"] != previous:
            return False
        previous = ledger.digest(turn)
    return True


# --------------------------------------------------------------------------
# B13 — the draw
# --------------------------------------------------------------------------


def b13_draw(seal: dict, seed_string: str) -> list[dict]:
    rng = _rng(seed_string)
    pool = []
    for entry in seal["sessions"]:
        if entry["half"] != "B":
            continue
        journal = _journal(entry)
        assumptions = {
            record["assumption_id"]: record
            for record in journal["assumptions"]
        }
        for turn in journal["turns"]:
            if not ledger.is_binding_dependent(turn):
                continue
            pool.append(
                {
                    "session_id": entry["session_id"],
                    "turn_index": turn["turn_index"],
                    "input_bytes": turn["input_bytes"],
                    "cited": turn["assumptions_cited"],
                    "cited_normal_forms": [
                        assumptions[item]["normal_form"]
                        for item in turn["assumptions_cited"]
                    ],
                }
            )
    pool.sort(key=lambda row: (row["session_id"], row["turn_index"]))
    drawn = rng.sample(pool, 20)
    rng.shuffle(drawn)
    for position, row in enumerate(drawn):
        row["audit_case"] = f"c{position:02d}"
    return drawn


# --------------------------------------------------------------------------
# the run
# --------------------------------------------------------------------------


SUPPLEMENTARY = {
    "is_supplementary": True,
    "authority": (
        "ROADMAP-v0.21 §4.0(1), and only its instrument-gap half: a control "
        "that provably NEVER EXECUTED is a bug, not a reading. Registered in "
        "experiments/session_ledger_prereg.json amendment 2, dated before "
        "this run."
    ),
    "supplements": "experiments/session_ledger_run.json",
    "the_original_is_never_edited_or_re_scored": True,
    "what_it_repairs": [
        "the capability-blind baseline's B4 arm, which compared the stateless "
        "replay against the RECORDED digest instead of against the stateless "
        "replay of the UNMUTATED journal, and therefore measured statelessness "
        "rather than mutation-response",
        "B6's generator, whose one-case-per-session rule capped it at 25 "
        "against a registered floor of >=30 — a ceiling below its own floor",
        "the verdict logic for every zero-flip clause, which checked the "
        "numerator and never the denominator",
    ],
    "what_it_cannot_do": (
        "un-fail R1. B10 read RED in the original run and B10 executed "
        "correctly, so it is a reading and it stands. This run re-scores B10 "
        "and gets the same answer, which is what a reading should do."
    ),
}


def run(repo_root: Path, *, supplementary: bool = False) -> dict:
    from resolver import default_index  # noqa: PLC0415
    from session_keys import SessionKeyRing  # noqa: PLC0415

    prereg = _load(PREREG)
    seal = _load(SEAL)
    seeds = prereg["blind_control"]["seeds_frozen_now"]
    index = default_index()
    keyring = SessionKeyRing.open(repo_root / ".runtime" / "session-keys.json")

    boot = CoreSession.boot(repo_root, offline=True)
    pins = ledger.pins(repo_root, boot.matrix)

    started = time.time()
    b1 = score_b1(seal)
    b2 = score_b2(seal, pins, index)
    b3 = score_b3(seal, pins, index)

    cases, key = build_cases(seal, seeds["mutation_mixer_seed"])
    blind = [
        {name: value for name, value in case.items()}
        for case in cases
    ]
    scored = score_cases(seal, blind, pins, index)

    # -- the join, and it is the LAST thing that happens ------------------
    arms: dict[str, list[dict]] = {"B4": [], "B5": [], "B6": []}
    for row in scored:
        arms[key[row["case_id"]]].append(row)

    b4_misses = [row for row in arms["B4"] if not row["flipped"]]
    b4 = {
        "verdict": "GREEN" if not b4_misses else "RED",
        "denominator": len(arms["B4"]),
        "denominator_source": (
            "every binding-dependent turn in half B — a turn with non-empty "
            "citations whose resolution.kind is `exact` (prereg amendment 1)"
        ),
        "responded": len(arms["B4"]) - len(b4_misses),
        "responded_by_a_typed_conflict_refusal": sum(
            1 for row in arms["B4"] if row["replayed_status"] == "refused"
        ),
        "standard": "100% or red, no tolerance, misses published individually",
        "misses_published_individually": b4_misses,
    }
    b5 = _zero_flip_clause("B5", arms["B5"])
    b6 = _zero_flip_clause("B6", arms["B6"])

    b7 = score_b7(seal)
    b8 = score_b8(seal, keyring, seeds["mutation_mixer_seed"])
    b10 = score_b10(seal, index)
    b11 = score_b11(seal)
    b12 = score_b12(seal)
    draw = b13_draw(seal, seeds["audit_draw_seed"])
    b13 = score_b13(draw)

    blind_b4 = score_baseline_b4(seal, blind, key, pins, index)
    baseline = {
        "what_it_is": (
            "§8's capability-blind baseline: a replayer that re-serves each "
            "line statelessly, ignoring Assumption records entirely"
        ),
        "b4_score": blind_b4["b4_responses"],
        "b4_must_be_zero_because": (
            "B4's mutation touches only the Assumption record and never the "
            "declaring line's input_bytes, which is all this arm reads. A "
            "score above zero means the mutation harness is leaking into "
            "input_bytes and the HARNESS is red, before anything is scored."
        ),
        **blind_b4,
        "b2_on_assumption_free_sessions": _baseline_b2(seal, pins, index),
    }
    baseline["verdict"] = (
        "GREEN"
        if baseline["b4_score"] == 0
        and baseline["b2_on_assumption_free_sessions"]["verdict"] == "GREEN"
        else "RED"
    )

    voided = bool(b5["flips"] or b6["flips"])
    r1_clauses = {
        "b2_replays": b2["verdict"] == "GREEN",
        "b4_green": b4["verdict"] == "GREEN",
        "b5_green": b5["verdict"] == "GREEN",
        "b6_green": b6["verdict"] == "GREEN",
        "b10_green": b10["verdict"] == "GREEN",
        "b12_corroborated": b12["verdict"] == "GREEN",
        "b13_at_or_above_16_of_20": b13["marked_yes"] >= 16,
    }
    r1 = {
        "clauses": r1_clauses,
        "verdict": "HOLDS" if all(r1_clauses.values()) else "FAILS",
        "served_claim_if_it_holds": prereg["result_gate"][
            "served_claim_if_R1_holds_verbatim"
        ],
    }

    return {
        "schema": RUN_SCHEMA,
        "design": "docs/DESIGN-session-ledger.md",
        "prereg": PREREG,
        "seal": SEAL,
        "slice": 1,
        "run_date": "2026-08-25",
        "registered_run": (
            "half B's first execution. Half A is scored beside it wherever a "
            "clause is corpus-wide, and no verdict below rests on half A."
        ),
        "determinism": prereg["determinism_clause"]["registered_as"],
        "runner_digest": _self_digest(),
        "recorder_code_digest": seal["recorder_code_digest"],
        "seeds": seeds,
        "elapsed_seconds": round(time.time() - started, 1),
        **({"supplementary": SUPPLEMENTARY} if supplementary else {}),
        "construction_gate": {
            "B1": b1,
            "B2": b2,
            "B3": b3,
            "B4": b4,
            "B5": b5,
            "B6": b6,
            "B7": b7,
            "B8": b8,
            "B9": {
                "verdict": "NEVER",
                "why": prereg["construction_gate"]["clauses"]["B9"]["why_never"],
            },
            "B10": b10,
            "B11": b11,
            "B12": b12,
            "B13": b13,
        },
        "blind_control": {
            "mixer": (
                "one sealed mixer, three arms, cases shuffled and carrying an "
                "opaque case_id and no arm field; the arm key is a separate "
                "object and the join is the last step of the run"
            ),
            "cases_total": len(cases),
            "arms_scored_blind": True,
            "voiding_sentence": prereg["blind_control"][
                "voiding_sentence_verbatim"
            ],
            "voided": voided,
            "why": (
                "a B5 or B6 flip means the replayer is keying on transcript "
                "bytes rather than assumption semantics"
                if voided
                else "no B5 or B6 flip; the voiding sentence does not fire"
            ),
        },
        "capability_blind_baseline": baseline,
        "result_gate": r1,
        "negative_honesty": (
            "sessions are reproducible, not correct. A wrong answer replays "
            "as faithfully as a right one, and nothing in this run is "
            "evidence that any answer is true."
        ),
        "non_claims": prereg["non_claims"]["verbatim"],
    }


def _zero_flip_clause(name: str, rows: list[dict]) -> dict:
    """A zero-flip clause scored on BOTH its numerator and its denominator.

    The first execution of this gate scored B6 green on 21 cases against a
    registered floor of >=30, because the verdict looked only at flips. A
    clause that cannot go red for having too few cases is a clause whose
    denominator nobody is watching, and this cycle's recurring catch is
    assertions written so they cannot go red.
    """

    flips = [row for row in rows if row["flipped"]]
    floor = REGISTERED_DENOMINATORS[name]
    if flips:
        verdict = "RED"
    elif len(rows) < floor:
        verdict = "SHORT OF DENOMINATOR"
    else:
        verdict = "GREEN"
    return {
        "verdict": verdict,
        "cases": len(rows),
        "registered_denominator": floor,
        "denominator_met": len(rows) >= floor,
        "flips": len(flips),
        "flip_rows": flips,
    }


def score_baseline_b4(
    seal: dict, cases: list[dict], key: dict, pins: dict, index
) -> dict:
    """§8's vacuity control, comparing the baseline against ITSELF.

    §8 asks whether the stateless replayer can **respond to** a B4 mutation:
    its output WITH the mutation against its output WITHOUT it. The first
    execution compared the stateless replay against the RECORDED digest
    instead, and a binding-dependent turn always diverges from its record
    under a stateless replayer whether or not anything was mutated — so that
    arm reported 58 and measured statelessness, not mutation-response. It
    never executed as designed, which is an instrument gap rather than a
    reading (ROADMAP-v0.21 §4.0(1)), and this is the repair.

    The expected answer is zero **by construction**: `_apply` touches only
    Assumption records and no turn's `input_bytes`, and `input_bytes` is all
    a stateless replay reads. Above zero means the mutation harness is
    leaking into `input_bytes` and the harness is red.
    """

    by_id = {entry["session_id"]: entry for entry in seal["sessions"]}
    responded = []
    checked = 0
    for case in cases:
        if key[case["case_id"]] != "B4":
            continue
        checked += 1
        journal = _journal(by_id[case["session_id"]])
        without = replay_session.replay(
            REPO, journal, shared_index=index, live_pins=pins, stateless=True
        )
        with_it = replay_session.replay(
            REPO,
            _apply(journal, case["mutation"]),
            shared_index=index,
            live_pins=pins,
            stateless=True,
        )
        left = _digest_at(without, case["watch_turn"])
        right = _digest_at(with_it, case["watch_turn"])
        if left != right:
            responded.append(
                {
                    "case_id": case["case_id"],
                    "session_id": case["session_id"],
                    "watch_turn": case["watch_turn"],
                }
            )
    return {
        "b4_cases_checked": checked,
        "b4_responses": len(responded),
        "b4_response_rows": responded,
        "comparison": (
            "stateless replay WITH the mutation against stateless replay "
            "WITHOUT it, at the watched turn — not against the recorded "
            "digest, which is what the first execution compared and why that "
            "arm never executed as designed"
        ),
    }


def _digest_at(report, turn_index: int) -> str:
    """The replayed digest at one turn, or the sentinel for `unchanged`.

    A replay report names only the turns that DIVERGED from the record, so
    'no divergence at this turn' means the replay reproduced the record
    there. Comparing two reports at one turn is therefore comparing which of
    them diverged and to what.
    """

    for item in report.divergences:
        if item["turn_index"] == turn_index:
            return item["replayed_digest"]
    return "reproduced-the-record"


def _baseline_b2(seal: dict, pins: dict, index) -> dict:
    rows = []
    for entry in seal["sessions"]:
        journal = _journal(entry)
        if any(journal["assumptions"]):
            continue
        report = replay_session.replay(
            REPO, journal, stateless=True, shared_index=index, live_pins=pins
        )
        rows.append(
            {
                "session_id": entry["session_id"],
                "turns_total": report.turns_total,
                "turns_reproduced": report.turns_reproduced,
            }
        )
    ok = all(row["turns_reproduced"] == row["turns_total"] for row in rows)
    return {
        "verdict": "GREEN" if ok and rows else "RED",
        "assumption_free_sessions": len(rows),
        "rows": rows,
    }


def score_b11(seal: dict) -> dict:
    result = subprocess.run(
        [sys.executable, str(REPO / "scripts" / "check_regeneration.py")],
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    revalidated = score_b1(seal)["clause_2_no_sealed_file_was_edited"]
    return {
        "verdict": (
            "GREEN"
            if result.returncode == 0 and revalidated["verdict"] == "GREEN"
            else "RED"
        ),
        "check_regeneration_exit": result.returncode,
        "check_regeneration_tail": result.stdout.strip().splitlines()[-1:],
        "seal_digests_revalidate": revalidated["verdict"],
        "journals_left_data_untouched": result.returncode == 0,
    }


def score_b13(draw: list[dict]) -> dict:
    """The audit's table. Marks are read from a committed file, never guessed."""

    path = REPO / AUDIT_MARKS
    if not path.exists():
        return {
            "verdict": "NOT YET MARKED",
            "drawn": draw,
            "marked_yes": 0,
            "why": (
                f"the draw is published in {AUDIT_MARKS}'s absence; the "
                "auditor marks each case and the run is re-read"
            ),
        }
    marks = json.loads(path.read_text(encoding="utf-8"))
    by_case = {row["audit_case"]: row for row in marks["marks"]}
    table = []
    for row in draw:
        mark = by_case.get(row["audit_case"], {})
        table.append({**row, "meaning_depends": mark.get("meaning_depends"),
                      "auditor_note": mark.get("note")})
    yes = sum(1 for row in table if row["meaning_depends"] is True)
    return {
        "verdict": "GREEN" if yes >= 16 else "BELOW FLOOR",
        "floor": 16,
        "of": 20,
        "marked_yes": yes,
        "table": table,
        "auditor": marks["auditor"],
        "auditor_independence": marks["auditor_independence"],
        "what_below_the_floor_would_mean": (
            "§11's cited-but-inert residual is promoted from named to "
            "measured against the claim, and the served line carries it"
        ),
        "and_the_limitation_of_an_easy_audit": marks["limitation"],
    }


def _self_digest() -> str:
    payload = Path(__file__).read_bytes().replace(b"\r\n", b"\n")
    return hashlib.sha256(payload).hexdigest()


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=ARTIFACT)
    ap.add_argument(
        "--supplementary",
        action="store_true",
        help=(
            "mark the artifact as §4.0(1)'s supplementary registered run and "
            "name the instrument gaps it repairs"
        ),
    )
    ap.add_argument(
        "--draw-only",
        action="store_true",
        help="publish B13's draw and stop, so the auditor marks a sealed sheet",
    )
    args = ap.parse_args(argv)

    if args.draw_only:
        prereg = _load(PREREG)
        seal = _load(SEAL)
        draw = b13_draw(
            seal, prereg["blind_control"]["seeds_frozen_now"]["audit_draw_seed"]
        )
        print(json.dumps(draw, indent=2, sort_keys=True))
        return 0

    payload = run(REPO, supplementary=args.supplementary)
    out = REPO / args.out
    out.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {args.out}")
    for name, clause in payload["construction_gate"].items():
        verdict = clause.get("verdict") or clause.get(
            "clause_2_no_sealed_file_was_edited", {}
        ).get("verdict")
        print(f"  {name}: {verdict}")
    print(f"  baseline: {payload['capability_blind_baseline']['verdict']}")
    print(f"  voided: {payload['blind_control']['voided']}")
    print(f"  R1: {payload['result_gate']['verdict']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
