#!/usr/bin/env python3
"""Seed data/information_theory/nodes.json.

This corpus exists to make one claim checkable by machine: *information
entropy and thermodynamic entropy are not an analogy, they are one structure*.

Shannon's H = -k sum_i p_i log p_i and the Boltzmann-Gibbs
S = -kB sum_i p_i ln p_i are the same functional of the same object -- a
probability distribution over microstates/messages -- differing only in the
constant out front, which fixes units (joules per kelvin vs bits). Shannon
took the name on von Neumann's advice; Jaynes (1957) argued the identity is
literal and rebuilt statistical mechanics on it; Landauer (1961) gave it a
price in joules. So the two nodes here are authored with *identical*
templates modulo slot names:

    infotheory.entropy.shannon_entropy
        INFORMATION = -(BASESCALE * sum_i WEIGHT_i * LOG(WEIGHT_i))
    physics.thermodynamics.gibbs_entropy      (scripts/seed_physics.py)
        ENTROPY     = -(SCALE     * sum_i PROBABILITY_i * LOG(PROBABILITY_i))

and land on one typed skeleton:

    ?0:V = neg(*(?1:P, sum⟨*(?2:V, LOG⟨?2:V⟩)⟩))

The load-bearing authoring details, all of them things the matcher can see:

1. The scale slot is `constant` (parameter-like, P) in both. kB is a fixed
   dimensional constant and so is 1/ln 2; if either had been left implicit the
   skeletons would differ by a whole factor and never meet.
2. The distribution slot occurs *twice* inside the sum body -- once as the
   weight, once inside the log. That repetition is the entire content of
   "expected log-probability", and it is what separates this skeleton from
   cross_entropy's, where the two occurrences are different slots.
3. Both carry the negation outside the constant. The matcher's `family` level
   would absorb a sign into a P-slot anyway, but typed twins are sign-exact,
   and a typed twin is the stronger claim we want here.

Two more cross-discipline hits were sought deliberately:

- `surprisal` (SURPRISAL = -(LOG(WEIGHT))) versus chemistry's pH
  (PH = -LOG(ACTIVITY)). This one fires as a *typed* twin, not merely a shape
  twin, because both corpora declare their two slots `variable`. It is the
  humblest twin in the graph and the most quietly correct: pH is the
  surprisal of a proton, measured in decimal digits.
- `entropy_inclusion_exclusion` uses the lattice heads CARD/MEET/JOIN that
  scripts/seed_logic.py established, so it matches
  settheory.cardinality.inclusion_exclusion_two_sets character for character.
  That is not a pun: Yeung's I-measure (1991) is a signed measure on the
  sigma-algebra generated by the variables, under which H is exactly CARD and
  mutual information is exactly the intersection term. Recording it with the
  set-theory heads makes the theorem the twin says it is.

Authoring constraints observed (all from docs/BACKLOG.md):

- `statement_id` may not contain `_` in its first segment, so ids are
  `infotheory.*` while the directory and `discipline` field are
  `information_theory` -- the same split the set-theory corpus already carries.
- `constantToken` has no `name` key.
- `symbol_lexicon.symbols` needs at least one scalar entry and cannot hold
  functionals, so LOG / ENTROPYOF / CAPMAX / CARD live in `functionals`.
- Identifiers starting `sum_ prod_ lim_ max_ min_` are silently parsed as
  prefix big-operators. That is used on purpose in the sum templates
  (`sum_i ...`) and avoided everywhere else; in particular channel capacity
  cannot be written as a `max_p` big-op without colliding with that namespace
  (and the grammar has no way to say "over the set of input distributions"
  regardless), so it uses an explicit `CAPMAX(objective, argument)` call. Call
  arguments are ORDERED for the matcher, so that convention -- objective
  first, optimized-over object second -- is fixed here and must be kept by
  anything added later.
"""

from __future__ import annotations

import json
from pathlib import Path


def sym(s, cat, role, desc, order=0):
    return {"symbol": s, "syntactic_category": cat, "semantic_role": role,
            "mathematical_order": order, "description": desc}


def op(symbol, name, arity=2, family="arithmetic"):
    return {"symbol": symbol, "name": name, "arity": arity, "operator_family": family}


def slot(sid, cat, role):
    return {"slot_id": sid, "syntactic_category": cat, "semantic_role": role}


def links(entailed_by=None, entails=None, equivalent_to=None,
          special_case_of=None, generalizes=None, composed_with=None):
    return {"entailed_by": entailed_by or [], "entails": entails or [],
            "equivalent_to": equivalent_to or [],
            "special_case_of": special_case_of or [],
            "generalizes": generalizes or [],
            "composed_with": composed_with or []}


def node(sid, title, cls, status, subfield, topic, ascii_, latex, forms,
         archetype, template, slots, invariants, symbols, operators,
         meaning, significance, conditions, provenance, disciplines=None,
         functionals=None, constants=None, index_sets=None, failure_modes=None,
         inferential_links=None, keywords=None, canonical_objects=None):
    context = {"disciplines": disciplines or ["information_theory"],
               "subfield": subfield, "topic": topic}
    if canonical_objects:
        context["canonical_objects"] = canonical_objects
    interpretation = {"statement_meaning": meaning,
                      "statistical_significance": significance,
                      "regularity_conditions": conditions}
    if failure_modes:
        interpretation["failure_modes"] = failure_modes
    out = {
        "statement_id": sid, "title": title, "statement_class": cls,
        "epistemic_status": status,
        "theory_context": context,
        "formal_statement": {"canonical_ascii": ascii_, "canonical_latex": latex,
                             "equivalent_forms": forms},
        "structural_signature": {"archetype_id": archetype,
                                 "anonymized_template": template,
                                 "slot_schema": slots, "invariants": invariants},
        "symbol_lexicon": {"symbols": symbols, "operators": operators,
                           "functionals": functionals or [],
                           "index_sets": index_sets or [],
                           "constants": constants or []},
        "semantic_interpretation": interpretation,
        "inferential_links": inferential_links or links(),
        "provenance": provenance,
    }
    if keywords:
        out["keywords"] = keywords
    return out


# --------------------------------------------------------------------------
# Lexicon fragments
# --------------------------------------------------------------------------

EQ = op("=", "equality", 2, "relational")
LE = op("<=", "less than or equal", 2, "relational")
GE = op(">=", "greater than or equal", 2, "relational")
ADD = op("+", "addition", 2, "arithmetic")
SUB = op("-", "subtraction", 2, "arithmetic")
MUL = op("*", "multiplication", 2, "arithmetic")
DIV = op("/", "division", 2, "arithmetic")
POW = op("^", "exponentiation", 2, "arithmetic")
NEG = op("-", "negation", 1, "arithmetic")
SUM = op("sum", "finite or countable summation over an index set", 1, "arithmetic")
EXPECT = op("E", "expectation under the stated distribution", 1, "stochastic")

LOG_FN = {"notation": "LOG(.)", "name": "logarithm", "input_arity": 1,
          "codomain": "extended reals",
          "description": "Logarithm of a positive argument. The base is a units "
                         "convention only: changing it multiplies the whole "
                         "expression by a constant, which is exactly the role "
                         "the BASESCALE slot plays."}

ENTROPYOF_FN = {"notation": "ENTROPYOF(.)", "name": "entropy functional",
                "input_arity": 1, "codomain": "non-negative reals",
                "description": "Shannon entropy of the joint distribution of its "
                               "arguments; with two arguments it is the joint "
                               "entropy H(X, Y). Written as a call rather than "
                               "expanded so that the additive decomposition of "
                               "mutual information is visible as structure."}

CAPMAX_FN = {"notation": "CAPMAX(objective, argument)", "name": "supremum over a family",
             "input_arity": 2, "codomain": "non-negative reals",
             "description": "Supremum of the first argument as the second ranges "
                            "over its admissible family. Introduced because the "
                            "template grammar has no binder for 'max over input "
                            "distributions', and because identifiers beginning "
                            "`max_` are parsed as prefix big-operators. Argument "
                            "order is fixed: objective first, optimized-over "
                            "object second."}

CARD_FN = {"notation": "CARD(.)", "name": "measure of an information atom",
           "input_arity": 1, "codomain": "reals",
           "description": "Yeung's I-measure mu*: the signed measure on the field "
                          "generated by the variables' sigma-algebras with "
                          "mu*(X~) = H(X). The same head the set-theory corpus "
                          "uses for cardinality, on purpose -- inclusion-exclusion "
                          "for counts and for entropies is one theorem about "
                          "finitely additive measures."}
MEET_FN = {"notation": "MEET(.,.)", "name": "lattice meet", "input_arity": 2,
           "description": "Greatest lower bound. Realized as intersection of "
                          "information atoms here, as conjunction in data/logic "
                          "and as set intersection in data/set_theory."}
JOIN_FN = {"notation": "JOIN(.,.)", "name": "lattice join", "input_arity": 2,
           "description": "Least upper bound. Realized as the atom of the joint "
                          "variable (X, Y) here, as disjunction in data/logic and "
                          "as set union in data/set_theory."}

IDX_ALPHABET = {"notation": "i in X", "domain": "a countable alphabet or state space",
                "description": "Index running over the symbols of the source "
                               "alphabet (equivalently, over microstates)."}
IDX_CODEWORDS = {"notation": "i in {1..N}", "domain": "finite set of codewords",
                 "description": "Index running over the codewords of a uniquely "
                                "decodable code."}

BASE_CONST = {"symbol": "k",
              "description": "Base-conversion constant. k = 1/ln 2 gives bits, "
                             "k = 1 nats, k = 1/ln 10 hartleys. Structurally the "
                             "same slot that carries kB in "
                             "physics.thermodynamics.gibbs_entropy, which is why "
                             "the two nodes are typed twins rather than merely "
                             "similar."}
RADIX_CONST = {"symbol": "D", "value": 2,
               "description": "Size of the code alphabet; 2 for binary codes. "
                              "Fixed in advance of the code, hence a constant "
                              "rather than a free parameter."}

# --------------------------------------------------------------------------
# Provenance
# --------------------------------------------------------------------------

SHANNON1948 = {"citation_key": "shannon1948",
               "bibliographic_entry": "Shannon, C. E. (1948). A Mathematical Theory of Communication. Bell System Technical Journal, 27(3), 379-423 and 27(4), 623-656.",
               "url": "https://doi.org/10.1002/j.1538-7305.1948.tb01338.x"}
COVER_THOMAS = {"citation_key": "cover2006",
                "bibliographic_entry": "Cover, T. M., Thomas, J. A. (2006). Elements of Information Theory (2nd ed.). Hoboken: Wiley-Interscience."}
MACKAY2003 = {"citation_key": "mackay2003",
              "bibliographic_entry": "MacKay, D. J. C. (2003). Information Theory, Inference, and Learning Algorithms. Cambridge: Cambridge University Press."}
KRAFT1949 = {"citation_key": "kraft1949",
             "bibliographic_entry": "Kraft, L. G. (1949). A Device for Quantizing, Grouping, and Coding Amplitude-Modulated Pulses. MSc thesis, Massachusetts Institute of Technology."}
MCMILLAN1956 = {"citation_key": "mcmillan1956",
                "bibliographic_entry": "McMillan, B. (1956). Two Inequalities Implied by Unique Decipherability. IRE Transactions on Information Theory, 2(4), 115-116."}
KL1951 = {"citation_key": "kullback1951",
          "bibliographic_entry": "Kullback, S., Leibler, R. A. (1951). On Information and Sufficiency. Annals of Mathematical Statistics, 22(1), 79-86."}
KULLBACK1959 = {"citation_key": "kullback1959",
                "bibliographic_entry": "Kullback, S. (1959). Information Theory and Statistics. New York: Wiley."}
JAYNES1957 = {"citation_key": "jaynes1957",
              "bibliographic_entry": "Jaynes, E. T. (1957). Information Theory and Statistical Mechanics. Physical Review, 106(4), 620-630."}
GIBBS1902 = {"citation_key": "gibbs1902",
             "bibliographic_entry": "Gibbs, J. W. (1902). Elementary Principles in Statistical Mechanics. New York: Charles Scribner's Sons."}
YEUNG1991 = {"citation_key": "yeung1991",
             "bibliographic_entry": "Yeung, R. W. (1991). A New Outlook on Shannon's Information Measures. IEEE Transactions on Information Theory, 37(3), 466-474."}
ARIMOTO1972 = {"citation_key": "arimoto1972",
               "bibliographic_entry": "Arimoto, S. (1972). An Algorithm for Computing the Capacity of Arbitrary Discrete Memoryless Channels. IEEE Transactions on Information Theory, 18(1), 14-20."}
BLAHUT1972 = {"citation_key": "blahut1972",
              "bibliographic_entry": "Blahut, R. E. (1972). Computation of Channel Capacity and Rate-Distortion Functions. IEEE Transactions on Information Theory, 18(4), 460-473."}
GOOD1952 = {"citation_key": "good1952",
            "bibliographic_entry": "Good, I. J. (1952). Rational Decisions. Journal of the Royal Statistical Society Series B, 14(1), 107-114."}
TRIBUS1971 = {"citation_key": "tribus1971",
              "bibliographic_entry": "Tribus, M., McIrvine, E. C. (1971). Energy and Information. Scientific American, 225(3), 179-188."}
CSISZAR1967 = {"citation_key": "csiszar1967",
               "bibliographic_entry": "Csiszar, I. (1967). Information-Type Measures of Difference of Probability Distributions and Indirect Observations. Studia Scientiarum Mathematicarum Hungarica, 2, 299-318."}

# --------------------------------------------------------------------------
# Nodes
# --------------------------------------------------------------------------

NODES = [
    node("infotheory.entropy.shannon_entropy", "Shannon Entropy",
         "definition", "formal", "source_coding", "entropy",
         "H = -(k * sum_i p_i*log(p_i))",
         "H(X) = -k \\sum_{i} p_i \\log p_i",
         [{"form_id": "bits", "notation_system": "ascii",
           "expression": "H(X) = -sum_i p_i*log2(p_i)",
           "scope_note": "k = 1/ln 2 folded into a base-2 logarithm; units are bits"},
          {"form_id": "expectation", "notation_system": "ascii",
           "expression": "H(X) = E[-log(p(X))]",
           "scope_note": "Entropy as the expected surprisal; the sum is the expectation written out"},
          {"form_id": "measure_theoretic", "notation_system": "measure_theoretic",
           "expression": "H(P) = -integral log(dP/dmu) dP",
           "scope_note": "Relative to a counting measure mu this reduces to the discrete sum"},
          {"form_id": "gibbs_units", "notation_system": "ascii",
           "expression": "S = kB * ln(2) * H(X)",
           "scope_note": "The same number in thermodynamic units; the whole content of the physics twin"}],
         "negated_scaled_expected_log",
         "INFORMATION = -(BASESCALE * sum_i WEIGHT_i * LOG(WEIGHT_i))",
         [slot("INFORMATION", "variable", "output"),
          slot("BASESCALE", "constant", "unit_scale_constant"),
          slot("WEIGHT_i", "variable", "distribution_weight")],
         ["The distribution slot occurs twice inside the summand -- once as the "
          "weight and once inside the logarithm. That repetition is the whole "
          "definition: it is what makes this an *expected* log-probability rather "
          "than a sum of unrelated terms, and it is what distinguishes this "
          "skeleton from cross_entropy's, where the two positions hold different "
          "slots.",
          "The scale slot is a fixed constant, not a free parameter: it only "
          "selects units (bits, nats, hartleys, joules per kelvin). Every claim "
          "about entropy is therefore invariant to it up to a positive factor.",
          "Non-negative, and zero exactly on point masses; maximized at the "
          "uniform distribution, where it equals LOG(N) -- see "
          "infotheory.entropy.uniform_entropy.",
          "Concave in the distribution and invariant under relabelling of the "
          "alphabet: entropy sees the multiset of probabilities, never the "
          "symbols carrying them.",
          "Additive over independent components, which is the property that "
          "forces the logarithm: Shannon's axioms (continuity, monotonicity in N, "
          "and the grouping/additivity law) determine this functional up to the "
          "scale constant."],
         [sym("H", "statistic", "output",
              "Entropy of the source distribution, in units fixed by k."),
          sym("p_i", "distribution", "distribution_weight",
              "Probability of the i-th symbol; p_i >= 0 and the p_i sum to one."),
          sym("X", "random_variable", "source",
              "The source random variable whose distribution is (p_i).")],
         [EQ, MUL, NEG, SUM, EXPECT],
         "Entropy is the negated, unit-scaled average of the logarithm of a "
         "distribution's own probabilities: the mean number of symbols needed to "
         "name an outcome drawn from it.",
         "The corpus's information/thermodynamics bridge. Its typed skeleton "
         "`?0:V = neg(*(?1:P, sum⟨*(?2:V, LOG⟨?2:V⟩)⟩))` is shared character for "
         "character with physics.thermodynamics.gibbs_entropy, and the two "
         "templates are authored deliberately identical modulo slot names because "
         "the claim is identity, not resemblance: the same functional of the same "
         "kind of object, with kB in the slot where information theory puts "
         "1/ln 2. Unlike the exponential twins that link compounding money to "
         "decaying nuclei -- analogies between unrelated subject matters -- this "
         "twin has a physical exchange rate attached to it. Landauer's bound "
         "prices one bit of erased information at kB*T*ln 2 joules, so the "
         "constant occupying the P slot is what converts between the two "
         "readings rather than what separates them.",
         ["A countable alphabet with a proper probability distribution",
          "Terms with p_i = 0 are read as 0 via the limit x*log(x) -> 0",
          "A fixed base, i.e. a fixed value of the scale constant, throughout an argument"],
         [SHANNON1948, COVER_THOMAS, JAYNES1957, MACKAY2003, TRIBUS1971],
         functionals=[LOG_FN],
         constants=[BASE_CONST],
         index_sets=[IDX_ALPHABET],
         failure_modes=[
             "The differential-entropy analogue for continuous variables is not a "
             "limit of this quantity -- it can be negative and is not invariant "
             "under change of variables -- so the discrete intuitions transfer "
             "only through relative entropy.",
             "Entropy is a property of a distribution, not of a string. Calling a "
             "particular observed sequence 'high entropy' conflates this with "
             "Kolmogorov complexity, which is a different (and uncomputable) "
             "quantity.",
             "Estimating H from finite samples by plugging in empirical "
             "frequencies is biased downward, badly so when the alphabet is large "
             "relative to the sample."],
         inferential_links=links(
             equivalent_to=["physics.thermodynamics.gibbs_entropy"],
             generalizes=["infotheory.entropy.uniform_entropy"],
             composed_with=["infotheory.entropy.surprisal",
                            "infotheory.divergence.cross_entropy"]),
         keywords=["entropy", "Shannon", "expected surprisal", "uncertainty",
                   "statistical mechanics", "bits"],
         canonical_objects=["discrete probability distribution", "source alphabet"]),

    node("infotheory.entropy.uniform_entropy", "Entropy of a Uniform Distribution",
         "theorem", "derived", "source_coding", "entropy",
         "H = k * log(N)", "H(X) = k \\log N",
         [{"form_id": "bits", "notation_system": "ascii",
           "expression": "H(X) = log2(N)",
           "scope_note": "Bits: a fair coin is 1, a fair byte is 8"},
          {"form_id": "hartley", "notation_system": "ascii",
           "expression": "H_0 = log(N)",
           "scope_note": "Hartley's 1928 measure, entropy before probabilities entered the account"},
          {"form_id": "boltzmann", "notation_system": "ascii",
           "expression": "S = kB*ln(W)",
           "scope_note": "Boltzmann's tombstone formula: the same statement for W equally likely microstates"}],
         "scaled_logarithm_of_count", "INFORMATION = BASESCALE * LOG(ALPHABETSIZE)",
         [slot("INFORMATION", "variable", "output"),
          slot("BASESCALE", "constant", "unit_scale_constant"),
          slot("ALPHABETSIZE", "variable", "count")],
         ["The distribution has vanished from the statement: only its support "
          "size remains. That collapse is the point of the node -- it is the one "
          "case where entropy is a function of a count.",
          "Upper bound as well as special case: H <= k*LOG(N) for every "
          "distribution on N symbols, with equality exactly at the uniform one, "
          "so this node doubles as the extremal statement.",
          "Logarithmic, hence additive over independent uniform components: two "
          "fair dice carry twice the entropy of one, not thirty-six times it.",
          "Same scale constant as infotheory.entropy.shannon_entropy, kept "
          "explicit so that the special-case relation is visible in the template "
          "rather than hidden in a base convention."],
         [sym("H", "statistic", "output", "Entropy of the uniform distribution."),
          sym("N", "variable", "count",
              "Number of equally likely outcomes (the support size).")],
         [EQ, MUL],
         "When every outcome is equally likely, the entropy is just the logarithm "
         "of how many outcomes there are, scaled to the chosen units.",
         "The specialization that makes the physics twin concrete: substituting "
         "p_i = 1/N into Shannon entropy turns "
         "`-(k * sum_i p_i*LOG(p_i))` into `k * LOG(N)`, and the corresponding "
         "substitution in physics.thermodynamics.gibbs_entropy turns Gibbs into "
         "Boltzmann's S = kB ln W. One derivation, run in two disciplines, "
         "arriving at two formulas that are usually taught in different buildings. "
         "Structurally it is also the corpus's cleanest instance of a slot "
         "disappearing under specialization: the summation and the repeated weight "
         "slot both vanish, leaving a scaled logarithm of a count.",
         ["N finite and at least 1",
          "All outcomes carry probability exactly 1/N",
          "Same base convention as the entropy it specializes"],
         [SHANNON1948, COVER_THOMAS, GIBBS1902, MACKAY2003],
         functionals=[LOG_FN],
         constants=[BASE_CONST],
         failure_modes=[
             "Read as a definition of entropy it is Hartley's measure, which "
             "ignores probabilities entirely and overstates the uncertainty of "
             "every non-uniform source.",
             "For countably infinite alphabets there is no uniform distribution, "
             "so the bound has no maximizer and entropy can be infinite."],
         inferential_links=links(
             special_case_of=["infotheory.entropy.shannon_entropy"]),
         keywords=["uniform distribution", "maximum entropy", "Hartley measure",
                   "Boltzmann entropy", "special case"]),

    node("infotheory.entropy.surprisal", "Surprisal (Self-Information)",
         "definition", "formal", "source_coding", "information_content",
         "h = -log(p)", "h(x) = -\\log p(x)",
         [{"form_id": "bits", "notation_system": "ascii",
           "expression": "h(x) = log2(1/p(x))",
           "scope_note": "Reciprocal form; makes the 'how many halvings' reading explicit"},
          {"form_id": "codelength", "notation_system": "ascii",
           "expression": "l(x) approx -log2(p(x))",
           "scope_note": "The ideal codeword length Shannon-Fano and arithmetic coding approach"},
          {"form_id": "bayes_update", "notation_system": "event_probability",
           "expression": "h(H | E) - h(H) = -log(Pr(E | H)/Pr(E))",
           "scope_note": "Bayes' rule in information form: the log-likelihood ratio is the change in surprisal"}],
         "negated_logarithmic_scale", "SURPRISAL = -(LOG(WEIGHT))",
         [slot("SURPRISAL", "variable", "output"),
          slot("WEIGHT", "variable", "input")],
         ["Strictly decreasing in the probability and unbounded above: an "
          "impossible-looking event carries arbitrarily much information, a "
          "certain one carries none.",
          "Turns products into sums, so the surprisal of independent events adds. "
          "This is the additivity requirement that forces a logarithm and nothing "
          "else.",
          "No scale constant appears here, unlike "
          "infotheory.entropy.shannon_entropy: the base of the logarithm fixes "
          "the units directly, and leaving the constant implicit is what lets "
          "this node meet chemistry's pH on the nose.",
          "Entropy is the expectation of this quantity, so every property of "
          "entropy that is linear in the summand descends from a property here."],
         [sym("h", "variable", "output",
              "Surprisal (self-information) of a single outcome."),
          sym("p", "distribution", "input",
              "Probability assigned to that outcome; strictly positive.")],
         [EQ, NEG],
         "The information carried by an outcome is the negative logarithm of its "
         "probability: rarer outcomes tell you more.",
         "The corpus's quietest cross-discipline twin, and one that was predicted "
         "before it was checked. Its typed skeleton `?0:V = neg(LOG⟨?1:V⟩)` is "
         "identical to chemistry.acid_base.ph_definition's -- pH is literally the "
         "surprisal of a proton, quoted in decimal digits instead of bits. The "
         "twin is *typed*, not merely shape-level, because both corpora "
         "independently declared their two slots `variable`; had either treated "
         "the argument as a parameter the match would have degraded. What the "
         "pair shows is that the negated-log-of-a-probability form is doing the "
         "same work in both places: compressing a multiplicative, many-orders-of-"
         "magnitude quantity onto an additive scale a human can hold in mind.",
         ["p strictly positive; the surprisal of an impossible outcome is +infinity by convention",
          "A fixed logarithm base throughout an argument"],
         [SHANNON1948, COVER_THOMAS, GOOD1952, MACKAY2003],
         functionals=[LOG_FN],
         failure_modes=[
             "Surprisal is a property of an outcome under an assumed model. "
             "Reporting a large surprisal as 'this event was informative' when "
             "the model itself is wrong measures the model, not the world.",
             "For continuous variables -log of a density is not information: it "
             "carries units and can be negative."],
         inferential_links=links(
             composed_with=["infotheory.entropy.shannon_entropy"]),
         keywords=["surprisal", "self-information", "log-probability",
                   "codeword length", "pH"]),

    node("infotheory.mutualinfo.mutual_information", "Mutual Information",
         "definition", "formal", "channel_coding", "dependence",
         "I = H(X) + H(Y) - H(X,Y)", "I(X;Y) = H(X) + H(Y) - H(X,Y)",
         [{"form_id": "conditional", "notation_system": "ascii",
           "expression": "I(X;Y) = H(X) - H(X | Y)",
           "scope_note": "Reduction in uncertainty about X from learning Y"},
          {"form_id": "divergence", "notation_system": "ascii",
           "expression": "I(X;Y) = KL(p(x,y) || p(x)*p(y))",
           "scope_note": "Relative entropy from the joint to the product of marginals; the form that proves I >= 0"},
          {"form_id": "double_sum", "notation_system": "ascii",
           "expression": "I(X;Y) = sum_x sum_y p(x,y)*log(p(x,y)/(p(x)*p(y)))"}],
         "additive_overlap_decomposition",
         "SHAREDINFORMATION = ENTROPYOF(FIRST) + ENTROPYOF(SECOND) - ENTROPYOF(FIRST, SECOND)",
         [slot("SHAREDINFORMATION", "variable", "output"),
          slot("FIRST", "random_variable", "component"),
          slot("SECOND", "random_variable", "component")],
         ["Symmetric in the two components, which the template shows directly: "
          "swapping FIRST and SECOND leaves the statement fixed (the joint term "
          "is symmetric as a distribution even though the call records an order).",
          "Zero exactly when the components are independent, since then the joint "
          "entropy is the sum of the marginals and the three terms cancel.",
          "Non-negative, but that is not visible in this template -- it comes from "
          "the divergence form and infotheory.divergence.gibbs_inequality.",
          "Bounded above by either marginal entropy: you cannot learn more about "
          "X than X contains.",
          "The subtraction is a correction for double counting, exactly as in "
          "inclusion-exclusion; see infotheory.mutualinfo.entropy_inclusion_exclusion "
          "for the same content written with the lattice heads."],
         [sym("I", "statistic", "output",
              "Mutual information between the two variables."),
          sym("X", "random_variable", "component", "First random variable."),
          sym("Y", "random_variable", "component", "Second random variable.")],
         [EQ, ADD, SUB],
         "The information two variables share is what their entropies count twice: "
         "add the separate uncertainties and subtract the joint uncertainty.",
         "An additive decomposition whose structure is the same double-counting "
         "correction that appears whenever a measure is applied to overlapping "
         "objects. Written this way it does *not* twin with "
         "settheory.cardinality.inclusion_exclusion_two_sets, because the matcher "
         "reads call heads literally and this node's left-hand side is a bare "
         "slot rather than a measure applied to a join. That near miss is the "
         "reason the companion node "
         "infotheory.mutualinfo.entropy_inclusion_exclusion exists: it states the "
         "same fact in the CARD/MEET/JOIN vocabulary and the twin then fires "
         "exactly. Keeping both is deliberate -- one is how the definition is "
         "written in every textbook, the other is what it is.",
         ["Discrete variables with a well-defined joint distribution",
          "All three entropies finite",
          "Same logarithm base in all three terms"],
         [SHANNON1948, COVER_THOMAS, MACKAY2003],
         functionals=[ENTROPYOF_FN],
         failure_modes=[
             "Zero mutual information means independence, not absence of "
             "structure that a particular model can use; and estimated mutual "
             "information is positively biased, so 'nonzero' from data is weak "
             "evidence of dependence.",
             "The three-variable analogue (interaction information) can be "
             "negative, so the inclusion-exclusion reading is a signed measure "
             "and not a measure of a set of points."],
         inferential_links=links(
             equivalent_to=["infotheory.mutualinfo.entropy_inclusion_exclusion"],
             composed_with=["infotheory.entropy.shannon_entropy",
                            "infotheory.divergence.kl_divergence"]),
         keywords=["mutual information", "dependence", "joint entropy",
                   "additive decomposition"]),

    node("infotheory.mutualinfo.entropy_inclusion_exclusion",
         "Inclusion-Exclusion for Entropy (I-Measure Form)",
         "theorem", "derived", "channel_coding", "dependence",
         "H(X,Y) = H(X) + H(Y) - I(X;Y)",
         "\\mu^{*}(\\tilde X \\cup \\tilde Y) = \\mu^{*}(\\tilde X) + \\mu^{*}(\\tilde Y) - \\mu^{*}(\\tilde X \\cap \\tilde Y)",
         [{"form_id": "entropy_notation", "notation_system": "ascii",
           "expression": "H(X, Y) = H(X) + H(Y) - I(X;Y)",
           "scope_note": "Standard notation: the joint entropy is the union term"},
          {"form_id": "imeasure", "notation_system": "measure_theoretic",
           "expression": "mu*(Xtilde union Ytilde) = mu*(Xtilde) + mu*(Ytilde) - mu*(Xtilde inter Ytilde)",
           "scope_note": "Yeung's I-measure on the field generated by the variables' sigma-algebras"},
          {"form_id": "conditional", "notation_system": "ascii",
           "expression": "H(X, Y) = H(X) + H(Y | X)",
           "scope_note": "Chain rule; the same identity with the overlap absorbed into the conditional term"}],
         "inclusion_exclusion_correction",
         "CARD(JOIN(FIRST, SECOND)) = CARD(FIRST) + CARD(SECOND) - CARD(MEET(FIRST, SECOND))",
         [slot("FIRST", "random_variable", "set_operand"),
          slot("SECOND", "random_variable", "set_operand")],
         ["The measure of a join is the sum of the measures minus the measure of "
          "the meet: finite additivity plus a correction for the shared part. "
          "Nothing in the statement is specific to entropy, which is exactly why "
          "it twins with the counting version.",
          "CARD here is Yeung's I-measure mu*, which is finitely additive but "
          "*signed*: unlike cardinality it can assign a negative value to an atom "
          "once three or more variables are involved. Two variables is precisely "
          "the range where the set picture is safe.",
          "The overlap term CARD(MEET(.,.)) is mutual information; the meet of "
          "independent variables has measure zero, which is the information-"
          "theoretic reading of disjointness.",
          "Symmetric in the two operands, and the argument order follows the "
          "convention fixed by scripts/seed_logic.py so the twin is exact."],
         [sym("H", "statistic", "output", "Entropy, read as the measure of an atom."),
          sym("I", "statistic", "overlap",
              "Mutual information, read as the measure of the intersection."),
          sym("X", "random_variable", "set_operand", "First random variable."),
          sym("Y", "random_variable", "set_operand", "Second random variable.")],
         [EQ, ADD, SUB],
         "Joint entropy is the sum of the two entropies minus the information they "
         "share, the same correction that counting a union requires.",
         "An exact typed twin of settheory.cardinality.inclusion_exclusion_two_sets, "
         "and the reason it fires is authorial: this node borrows the CARD / MEET / "
         "JOIN heads that scripts/seed_logic.py introduced for the Boolean lattice "
         "instead of writing H, comma and semicolon. That is a translation, not a "
         "disguise -- Yeung's I-measure theorem says there is a signed measure "
         "mu* on the field generated by the variables with mu*(Xtilde) = H(X) and "
         "mu*(Xtilde inter Ytilde) = I(X;Y), so entropy really is a measure and "
         "this really is inclusion-exclusion. The pair with the set-theory node "
         "gives the corpus a three-corpus family (sets, logic, information) around "
         "one measure-theoretic fact, and it shows the price the matcher extracts: "
         "twins fire on notation, so a shared abstraction has to be *adopted* "
         "before a genuine shared structure becomes visible.",
         ["Discrete variables with finite entropies",
          "Two variables only: the signed I-measure admits negative atoms from "
          "three variables onward",
          "Same logarithm base throughout"],
         [YEUNG1991, COVER_THOMAS, SHANNON1948],
         functionals=[CARD_FN, MEET_FN, JOIN_FN],
         failure_modes=[
             "The Venn-diagram intuition breaks at three variables: the triple "
             "'intersection' I(X;Y;Z) can be negative, so no set of points "
             "realizes the picture.",
             "mu* is not a probability measure and its atoms are not events; "
             "reading CARD as a count of anything is a category error."],
         inferential_links=links(
             equivalent_to=["infotheory.mutualinfo.mutual_information"],
             composed_with=["settheory.cardinality.inclusion_exclusion_two_sets"]),
         keywords=["inclusion-exclusion", "I-measure", "joint entropy",
                   "mutual information", "signed measure"]),

    node("infotheory.channel.channel_capacity", "Channel Capacity",
         "definition", "formal", "channel_coding", "capacity",
         "C = max over p(x) of I(X;Y)",
         "C = \\max_{p(x)} I(X;Y)",
         [{"form_id": "supremum", "notation_system": "ascii",
           "expression": "C = sup_{p(x)} I(X;Y)",
           "scope_note": "Supremum form, needed when the input alphabet is infinite"},
          {"form_id": "operational", "notation_system": "ascii",
           "expression": "C = sup{R : R is achievable with vanishing error probability}",
           "scope_note": "The operational definition the noisy-channel coding theorem proves equal to the formula"},
          {"form_id": "gaussian", "notation_system": "ascii",
           "expression": "C = (1/2)*log2(1 + S/N)",
           "scope_note": "Shannon-Hartley: the maximization solved in closed form for an AWGN channel"}],
         "constrained_supremum", "CAPACITY = CAPMAX(SHAREDINFORMATION, INPUTDISTRIBUTION)",
         [slot("CAPACITY", "variable", "output"),
          slot("SHAREDINFORMATION", "variable", "objective"),
          slot("INPUTDISTRIBUTION", "distribution", "optimized_argument")],
         ["A variational statement, not an evaluation: the channel is fixed and "
          "the *input distribution* is free, which is what makes capacity a "
          "property of the channel alone.",
          "The objective is concave in the input distribution over a convex "
          "(simplex) feasible set, so the maximum is attained and is a global "
          "one; Blahut-Arimoto exploits exactly this.",
          "Bounded above by the log of the input alphabet size, since mutual "
          "information cannot exceed the input entropy.",
          "Zero exactly for a channel whose output distribution does not depend "
          "on the input.",
          "The CAPMAX head is an authoring device, not notation anyone writes: "
          "the template grammar has no binder for 'maximize over a family', and "
          "an identifier spelled `max_p` would be silently parsed as a prefix "
          "big-operator (docs/BACKLOG.md). Consequently this node cannot twin "
          "with any optimization elsewhere in the corpus until the grammar grows "
          "a real binder -- the structural claim is quarantined inside one "
          "opaque call."],
         [sym("C", "statistic", "output", "Channel capacity in bits per channel use."),
          sym("I", "statistic", "objective",
              "Mutual information between channel input and output."),
          sym("p", "distribution", "optimized_argument",
              "Input distribution ranging over the probability simplex on the input alphabet.")],
         [EQ],
         "Capacity is the largest mutual information any input distribution can "
         "push through a fixed channel.",
         "The node where the template grammar runs out. Every other statement in "
         "this corpus is an expression that could be evaluated once its slots are "
         "filled; capacity is a maximization over a function space, and the "
         "grammar -- identifiers, arithmetic, calls, one prefix big-operator "
         "family, relations -- has no binder to express it. Writing "
         "`max_p I(X;Y)` would collide with the `max_` big-operator namespace "
         "recorded in docs/BACKLOG.md and would in any case lose the constraint "
         "set. The honest workaround is an opaque `CAPMAX(objective, argument)` "
         "call with a fixed argument order, which parses cleanly and states the "
         "dependency structure while conceding that the *internal* structure of "
         "the optimization is invisible to the matcher. That concession is worth "
         "recording: it marks the boundary between what this corpus can compare "
         "and what it can only name, and it is the strongest argument in the "
         "corpus for adding binder syntax.",
         ["A discrete memoryless channel with a fixed transition law",
          "Input distributions range over the probability simplex on the input alphabet",
          "The supremum is a maximum when the input alphabet is finite"],
         [SHANNON1948, COVER_THOMAS, ARIMOTO1972, BLAHUT1972],
         functionals=[CAPMAX_FN],
         failure_modes=[
             "Capacity is an asymptotic promise about arbitrarily long block "
             "codes; at finite blocklength the achievable rate falls short by a "
             "term in the channel dispersion, so quoting C as an engineering "
             "throughput overstates it.",
             "The maximizing input distribution is generally not uniform, and "
             "assuming it is understates capacity for asymmetric channels.",
             "Feedback does not increase capacity for memoryless channels but "
             "does for channels with memory; transplanting the formula is unsafe."],
         inferential_links=links(
             composed_with=["infotheory.mutualinfo.mutual_information"]),
         keywords=["channel capacity", "noisy-channel coding theorem",
                   "optimization", "Blahut-Arimoto", "grammar limit"]),

    node("infotheory.coding.kraft_inequality", "Kraft-McMillan Inequality",
         "theorem", "derived", "source_coding", "prefix_codes",
         "sum_i D^(-l_i) <= 1", "\\sum_{i} D^{-\\ell_i} \\le 1",
         [{"form_id": "binary", "notation_system": "ascii",
           "expression": "sum_i 2^(-l_i) <= 1",
           "scope_note": "Binary codes, the case in practice"},
          {"form_id": "converse", "notation_system": "ascii",
           "expression": "if sum_i D^(-l_i) <= 1 then a prefix code with lengths l_i exists",
           "scope_note": "The existence half; the inequality characterizes achievable length profiles"},
          {"form_id": "probability_reading", "notation_system": "ascii",
           "expression": "q_i = D^(-l_i) defines a sub-probability distribution",
           "scope_note": "The reading that turns the inequality into the entropy bound"}],
         "bounded_negative_exponential_sum", "sum_i RADIX^(-(CODELENGTH_i)) <= 1",
         [slot("RADIX", "constant", "alphabet_size"),
          slot("CODELENGTH_i", "variable", "codeword_length")],
         ["A budget constraint: each codeword of length l consumes a D^(-l) share "
          "of the code space, and the shares cannot exceed the whole.",
          "The relation is `<=`, not `=`, and the slack is real -- codes with "
          "strict inequality exist and are simply wasteful.",
          "Both a necessary and a sufficient condition, which is unusual: the "
          "inequality is necessary for every uniquely decodable code (McMillan) "
          "and sufficient for the existence of a prefix code (Kraft), so it "
          "characterizes achievable length profiles exactly.",
          "The exponent slot is negated, which makes the terms decreasing in "
          "length; the alphabet size is a constant fixed before the code, not a "
          "free parameter.",
          "Substituting the ideal lengths l_i = -log_D(p_i) makes the sum equal "
          "1 exactly, which is how this inequality becomes the entropy lower "
          "bound on expected code length."],
         [sym("l_i", "variable", "codeword_length",
              "Length of the i-th codeword, a positive integer."),
          sym("D", "constant", "alphabet_size",
              "Size of the code alphabet; 2 for binary codes.")],
         [LE, POW, NEG, SUM],
         "The codeword lengths of any uniquely decodable code satisfy a budget "
         "constraint, and any lengths satisfying it can be realized by a prefix "
         "code.",
         "The corpus's only inequality-rooted node with a big-operator on the "
         "left and a bare numeral on the right, which makes its skeleton "
         "`sum⟨^(?0:P, neg(?1:V))⟩ <= 1` a singleton so far. That is worth "
         "stating plainly: not every node earns a twin, and a corpus that only "
         "admitted twinnable statements would be evidence of selection rather "
         "than of structure. What the node does supply is the bridge from the "
         "entropy definitions to *codes*: read D^(-l_i) as a sub-probability and "
         "the inequality becomes the reason expected code length cannot fall "
         "below entropy, which is the operational meaning of "
         "infotheory.entropy.shannon_entropy.",
         ["A uniquely decodable code over an alphabet of size D",
          "Finitely or countably many codewords",
          "Lengths are positive integers"],
         [KRAFT1949, MCMILLAN1956, COVER_THOMAS, SHANNON1948],
         constants=[RADIX_CONST],
         index_sets=[IDX_CODEWORDS],
         failure_modes=[
             "The inequality constrains lengths, not the code: satisfying it does "
             "not make a *given* code prefix-free, it only guarantees that some "
             "code with those lengths is.",
             "Integer lengths mean the entropy bound is generally not attained; "
             "the gap is under one symbol per codeword (Shannon-Fano) and "
             "vanishes only when the probabilities are D-adic."],
         inferential_links=links(
             composed_with=["infotheory.entropy.shannon_entropy",
                            "infotheory.entropy.surprisal"]),
         keywords=["Kraft inequality", "McMillan", "prefix code",
                   "unique decodability", "code length"]),

    node("infotheory.divergence.cross_entropy", "Cross-Entropy",
         "definition", "formal", "source_coding", "divergence",
         "H(p, q) = -(k * sum_i p_i*log(q_i))",
         "H(p, q) = -k \\sum_i p_i \\log q_i",
         [{"form_id": "decomposition", "notation_system": "ascii",
           "expression": "H(p, q) = H(p) + KL(p || q)",
           "scope_note": "Entropy plus the penalty for using the wrong model; the identity that makes cross-entropy a training objective"},
          {"form_id": "expectation", "notation_system": "ascii",
           "expression": "H(p, q) = E_p[-log(q(X))]",
           "scope_note": "Expected surprisal of the truth under the model"},
          {"form_id": "log_loss", "notation_system": "ascii",
           "expression": "L = -(1/n)*sum_j log(q(y_j))",
           "scope_note": "Empirical form: the log loss minimized in classification, with p the empirical distribution"}],
         "negated_scaled_cross_log",
         "CROSSINFORMATION = -(BASESCALE * sum_i WEIGHT_i * LOG(MODELWEIGHT_i))",
         [slot("CROSSINFORMATION", "variable", "output"),
          slot("BASESCALE", "constant", "unit_scale_constant"),
          slot("WEIGHT_i", "variable", "true_weight"),
          slot("MODELWEIGHT_i", "variable", "model_weight")],
         ["Two distinct distribution slots where "
          "infotheory.entropy.shannon_entropy has one repeated slot. That single "
          "difference is the whole distinction between entropy and cross-entropy, "
          "and it is exactly what keeps the two skeletons apart in the matcher: "
          "`LOG⟨?2:V⟩` against `LOG⟨?3:V⟩`.",
          "Asymmetric in its two arguments: the weights come from the truth and "
          "the logarithms from the model. Swapping them is a different quantity.",
          "Bounded below by the entropy of the first argument, with equality "
          "exactly when the two distributions agree -- which is "
          "infotheory.divergence.gibbs_inequality restated.",
          "Linear in the true distribution, so an empirical average over samples "
          "is an unbiased estimate of it; this is why it is the loss function "
          "rather than KL divergence, whose extra term does not depend on the "
          "model at all."],
         [sym("H", "statistic", "output",
              "Cross-entropy of the model distribution relative to the truth."),
          sym("p_i", "distribution", "true_weight",
              "Probability under the data-generating distribution."),
          sym("q_i", "distribution", "model_weight",
              "Probability under the model; must be positive wherever p_i is.")],
         [EQ, MUL, NEG, SUM, EXPECT],
         "Cross-entropy is the average surprisal you incur when the world follows "
         "one distribution and your code (or model) was built for another.",
         "A near miss by design. Its skeleton "
         "`?0:V = neg(*(?1:P, sum⟨*(?2:V, LOG⟨?3:V⟩)⟩))` differs from Shannon "
         "entropy's only in that the two inner slot positions are filled by "
         "different slots, so no twin fires -- and that is the correct answer. "
         "The pair is the sharpest demonstration in the corpus that the matcher "
         "keys on *slot reuse* and not just on operator shape: the structural "
         "difference between measuring your own uncertainty and paying for "
         "someone else's model is one repeated placeholder. It is also the point "
         "where the corpus touches machine learning, since log loss is this "
         "quantity with the empirical distribution in the first slot.",
         ["q_i > 0 wherever p_i > 0 (absolute continuity), else the value is infinite",
          "Both arguments are distributions on the same alphabet",
          "Same logarithm base as the entropy it is compared with"],
         [COVER_THOMAS, KL1951, GOOD1952, MACKAY2003],
         functionals=[LOG_FN],
         constants=[BASE_CONST],
         index_sets=[IDX_ALPHABET],
         failure_modes=[
             "A model that assigns probability zero to an observed outcome makes "
             "the cross-entropy infinite, which is why practical training clips "
             "or smooths the model's probabilities.",
             "Cross-entropy is not a distance: it does not vanish when the "
             "arguments agree (it equals the entropy there), and it is not "
             "symmetric."],
         inferential_links=links(
             composed_with=["infotheory.entropy.shannon_entropy",
                            "infotheory.divergence.kl_divergence"]),
         keywords=["cross-entropy", "log loss", "model mismatch", "coding cost"]),

    node("infotheory.divergence.kl_divergence",
         "Kullback-Leibler Divergence (Relative Entropy)",
         "definition", "formal", "source_coding", "divergence",
         "KL(p || q) = k * sum_i p_i*log(p_i/q_i)",
         "D_{KL}(p \\| q) = k \\sum_i p_i \\log \\frac{p_i}{q_i}",
         [{"form_id": "expectation", "notation_system": "ascii",
           "expression": "KL(p || q) = E_p[log(p(X)/q(X))]",
           "scope_note": "Expected log-likelihood ratio under the first argument"},
          {"form_id": "cross_entropy_form", "notation_system": "ascii",
           "expression": "KL(p || q) = H(p, q) - H(p)",
           "scope_note": "Excess coding cost: bits paid for using q's code on p's data"},
          {"form_id": "measure_theoretic", "notation_system": "measure_theoretic",
           "expression": "KL(P || Q) = integral log(dP/dQ) dP",
           "scope_note": "General form via the Radon-Nikodym derivative; requires P << Q"}],
         "scaled_expected_log_ratio",
         "DIVERGENCE = BASESCALE * sum_i WEIGHT_i * LOG(WEIGHT_i / MODELWEIGHT_i)",
         [slot("DIVERGENCE", "variable", "output"),
          slot("BASESCALE", "constant", "unit_scale_constant"),
          slot("WEIGHT_i", "variable", "true_weight"),
          slot("MODELWEIGHT_i", "variable", "model_weight")],
         ["The true-distribution slot occurs twice -- as the weight and in the "
          "numerator of the ratio -- while the model slot occurs once, in the "
          "denominator. That asymmetric reuse pattern is the reason KL is not a "
          "metric, visible in the template without any semantics.",
          "No leading negation, unlike entropy and cross-entropy: the ratio "
          "inside the logarithm has already absorbed the sign, since "
          "log(p/q) = log p - log q.",
          "Non-negative and zero exactly when the two distributions agree "
          "(infotheory.divergence.gibbs_inequality), so it behaves like a "
          "directed distance without satisfying the triangle inequality.",
          "Invariant under invertible reparameterization of the alphabet, which "
          "differential entropy is not -- this is why relative entropy, not "
          "entropy, is the quantity that survives the passage to continuous "
          "variables.",
          "Additive over independent products, so divergences of product "
          "distributions add."],
         [sym("KL", "statistic", "output",
              "Relative entropy from the model to the truth."),
          sym("p_i", "distribution", "true_weight",
              "Probability under the reference (data-generating) distribution."),
          sym("q_i", "distribution", "model_weight",
              "Probability under the compared distribution.")],
         [EQ, MUL, DIV, SUM, EXPECT],
         "Relative entropy is the average log-ratio between two distributions "
         "weighted by the first: the extra cost, per symbol, of believing the "
         "second when the first is true.",
         "Structurally the entropy skeleton with the logarithm's argument opened "
         "up into a ratio, and semantically the quantity that unifies most of "
         "this corpus: entropy is the divergence from the uniform distribution up "
         "to a constant, mutual information is the divergence from the joint to "
         "the product of marginals, and cross-entropy is this plus the entropy. "
         "The physics reading is just as direct -- for a system held away from "
         "equilibrium, KL from the actual state to the equilibrium state is the "
         "available free energy divided by kB*T, so the same functional that "
         "prices a bad code prices a thermodynamic disequilibrium. That is the "
         "entropy bridge again, one derivative further along.",
         ["Absolute continuity: q_i > 0 wherever p_i > 0",
          "Terms with p_i = 0 are read as 0",
          "Both arguments are distributions on the same alphabet"],
         [KL1951, KULLBACK1959, COVER_THOMAS, CSISZAR1967],
         functionals=[LOG_FN],
         constants=[BASE_CONST],
         index_sets=[IDX_ALPHABET],
         failure_modes=[
             "Not symmetric and not a metric; reporting 'the KL distance' between "
             "two models without saying which is the reference is meaningless.",
             "Infinite whenever the model gives zero probability to something the "
             "truth gives positive probability, so it is unusable as a raw "
             "objective against sparse empirical distributions.",
             "The two directions optimize differently -- KL(p||q) is "
             "mode-covering, KL(q||p) mode-seeking -- and swapping them silently "
             "changes what a fitted model looks like."],
         inferential_links=links(
             entails=["infotheory.divergence.gibbs_inequality"],
             composed_with=["infotheory.divergence.cross_entropy",
                            "infotheory.mutualinfo.mutual_information"]),
         keywords=["Kullback-Leibler", "relative entropy", "divergence",
                   "log-likelihood ratio", "free energy"]),

    node("infotheory.divergence.gibbs_inequality",
         "Gibbs' Inequality (Non-Negativity of Relative Entropy)",
         "theorem", "derived", "source_coding", "divergence",
         "k * sum_i p_i*log(p_i/q_i) >= 0",
         "k \\sum_i p_i \\log \\frac{p_i}{q_i} \\ge 0",
         [{"form_id": "divergence_form", "notation_system": "ascii",
           "expression": "KL(p || q) >= 0, with equality iff p = q"},
          {"form_id": "cross_entropy_form", "notation_system": "ascii",
           "expression": "H(p) <= H(p, q)",
           "scope_note": "The coding reading: no code beats the one built for the true distribution"},
          {"form_id": "jensen", "notation_system": "ascii",
           "expression": "E_p[-log(q(X)/p(X))] >= -log(E_p[q(X)/p(X)]) = -log(1) = 0",
           "scope_note": "The proof in one line: Jensen's inequality applied to the convex function -log"}],
         "non_negative_expected_log_ratio",
         "BASESCALE * sum_i WEIGHT_i * LOG(WEIGHT_i / MODELWEIGHT_i) >= 0",
         [slot("BASESCALE", "constant", "unit_scale_constant"),
          slot("WEIGHT_i", "variable", "true_weight"),
          slot("MODELWEIGHT_i", "variable", "model_weight")],
         ["Relational rather than definitional: the top node is `>=` against the "
          "numeral 0, so unlike every equation in this corpus the statement is "
          "irreversible and carries no output slot at all.",
          "Equality holds exactly when the two distributions coincide, which is "
          "what makes relative entropy usable as a discrepancy despite not being "
          "a metric.",
          "A one-line consequence of the convexity of -log via Jensen's "
          "inequality; the same convexity argument gives the whole f-divergence "
          "family its non-negativity, which is Csiszar's generalization.",
          "The sign of the scale constant matters here in a way it does not "
          "elsewhere: a negative base constant would flip the inequality, so the "
          "constant is implicitly positive."],
         [sym("p_i", "distribution", "true_weight",
              "Probability under the reference distribution."),
          sym("q_i", "distribution", "model_weight",
              "Probability under the compared distribution."),
          sym("KL", "statistic", "quantity_bounded",
              "The relative entropy being bounded below.")],
         [GE, MUL, DIV, SUM],
         "Relative entropy is never negative, and vanishes only when the two "
         "distributions are identical.",
         "The theorem that turns the divergence definition into a tool: without "
         "it, KL would be an expression rather than a discrepancy. It also "
         "underwrites three other nodes here -- mutual information is "
         "non-negative because it is a KL, entropy is maximized at the uniform "
         "distribution because the gap is a KL, and expected code length cannot "
         "beat entropy because the shortfall is a KL against the Kraft "
         "sub-distribution. Its epistemic status is `derived` rather than "
         "`formal` for exactly that reason: it is proved, in one Jensen step, "
         "from the convexity of the logarithm, not posited.",
         ["Both arguments are distributions on the same alphabet",
          "q_i > 0 wherever p_i > 0",
          "Positive base constant"],
         [COVER_THOMAS, KL1951, CSISZAR1967, GIBBS1902],
         functionals=[LOG_FN],
         constants=[BASE_CONST],
         index_sets=[IDX_ALPHABET],
         failure_modes=[
             "Equality 'iff p = q' is up to sets of probability zero under p; two "
             "distributions differing where p vanishes still give divergence 0.",
             "The inequality says nothing about magnitude, so a small KL does not "
             "bound the difference in expectations of unbounded functions; "
             "Pinsker's inequality is needed for that and only bounds total "
             "variation."],
         inferential_links=links(
             entailed_by=["infotheory.divergence.kl_divergence"],
             composed_with=["infotheory.divergence.cross_entropy",
                            "infotheory.mutualinfo.mutual_information"]),
         keywords=["Gibbs inequality", "non-negativity", "Jensen",
                   "relative entropy", "convexity"]),
]


def main() -> None:
    corpus = {
        "schema": "../../schema/equation-node.schema.json",
        "corpus_id": "information_theory.foundations.v1",
        "discipline": "information_theory",
        "version": "1.0.0-alpha",
        "statement_nodes": NODES,
    }
    out = Path("data/information_theory/nodes.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(corpus, indent=2, ensure_ascii=False) + "\n",
                   encoding="utf-8")
    print(f"wrote {len(NODES)} information theory nodes -> {out}")


if __name__ == "__main__":
    main()
